name: phpMyAdmin + NRO Setup with Cloudflared Tunnel (sequential)

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1️⃣ Cài MySQL, PHP, phpMyAdmin, SSH
      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-server php php-mbstring php-zip php-gd php-json php-curl php-mysql unzip wget openssh-client

      # 2️⃣ Dừng MySQL nếu đang chạy
      - name: Stop MySQL service
        run: |
          sudo systemctl stop mysql || true

      # 3️⃣ Khởi động MySQL bỏ qua kiểm tra user/password
      - name: Start MySQL with skip-grant-tables
        run: |
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld
          sudo mysqld_safe --skip-grant-tables --skip-networking &>/dev/null &
          sleep 8

      # 4️⃣ Set root password
      - name: Set root password
        run: |
          mysql -uroot <<'SQL'
          FLUSH PRIVILEGES;
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
          FLUSH PRIVILEGES;
          SQL
          echo "✅ Root password set to 'root'"

      # 5️⃣ Restart MySQL bình thường
      - name: Restart MySQL service
        run: |
          sudo pkill mysqld || true
          sudo systemctl start mysql
          sleep 5
          mysql -uroot -proot -e "SELECT VERSION();" || true
          echo "✅ MySQL restarted and accessible."

      # 6️⃣ Tạo database nro_acc và nro_data từ SQL file (nếu có)
      - name: Create databases and import SQL
        run: |
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS nro_acc;"
          if [ -f ./nro_acc.sql ]; then
            mysql -uroot -proot nro_acc < ./nro_acc.sql || echo "⚠️ Import nro_acc.sql failed"
          else
            echo "⚠️ ./nro_acc.sql not found, skipping import"
          fi

          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS nro_data;"
          if [ -f ./nro_data.sql ]; then
            mysql -uroot -proot nro_data < ./nro_data.sql || echo "⚠️ Import nro_data.sql failed"
          else
            echo "⚠️ ./nro_data.sql not found, skipping import"
          fi

          echo "✅ Databases created/import attempted."

      # 7️⃣ Tạo user admin (tùy chọn)
      - name: Create admin user
        run: |
          mysql -uroot -proot -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '123456';"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
          echo "✅ Admin user created."

      # === PHPMYADMIN PHASE ===
      - name: Install phpMyAdmin
        run: |
          wget -q https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip -O pma.zip
          unzip -q pma.zip
          mv phpMyAdmin-* phpmyadmin || true
          # Start php built-in server on 8080 (background)
          sudo php -S 0.0.0.0:8080 -t phpmyadmin &> /tmp/php_builtin.log &
          sleep 2
          echo "✅ phpMyAdmin built-in server started (port 8080)."
          tail -n 40 /tmp/php_builtin.log || true

      - name: Install cloudflared (for phpMyAdmin)
        run: |
          echo "📥 Installing cloudflared..."
          sudo wget -q -O /usr/local/bin/cloudflared \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          sudo chmod +x /usr/local/bin/cloudflared
          /usr/local/bin/cloudflared --version || true

      - name: Start cloudflared tunnel for phpMyAdmin and show public URL
        run: |
          echo "🌐 Starting cloudflared tunnel to http://localhost:8080 ..."
          nohup /usr/local/bin/cloudflared tunnel --url http://localhost:8080 --no-autoupdate > cloudflared_pma.log 2>&1 &
          sleep 8
          if grep -Eo 'https?://[^ ]+trycloudflare.com' cloudflared_pma.log | head -n1 > /tmp/pma_url; then
            echo "✅ Public phpMyAdmin URL (ephemeral):"
            cat /tmp/pma_url
          else
            echo "⚠️ Không tìm thấy URL trong cloudflared_pma.log. Dump file để debug:"
            sed -n '1,200p' cloudflared_pma.log || true
          fi

      # === SITE PHASE (chạy sau khi phpMyAdmin đã up) ===
      - name: Download new3.zip from GitHub release
        run: |
          ZIP_URL="https://github.com/hrjfjtjtntnfn/lode/releases/download/V.838383/new3.zip"
          echo "🔽 Downloading from $ZIP_URL ..."
          wget -q "$ZIP_URL" -O new3.zip || { echo "⚠️ Failed to download ZIP"; exit 1; }
          unzip -q new3.zip || true
          if [ -d "new3/new3" ]; then mv new3/new3/* new3/ || true; fi
          echo "✅ Extracted successfully."
          ls -al new3 || true

      - name: Install Apache & PHP and deploy files
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apache2 php libapache2-mod-php unzip
          sudo a2enmod rewrite || true
          sudo service apache2 stop || true
          sudo mkdir -p /var/www/html
          sudo cp -r new3/* /var/www/html/ || true
          sudo rm -f /var/www/html/index.html || true
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          echo "✅ Apache & PHP deployed to /var/www/html."

      - name: Configure Apache for .htaccess and custom port 5000
        run: |
          sudo bash -c 'cat >/etc/apache2/sites-available/000-default.conf <<EOF
          <VirtualHost *:5000>
              DocumentRoot /var/www/html
              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
          EOF'
          sudo sed -i "s/Listen 80/Listen 5000/" /etc/apache2/ports.conf || true
          sudo apachectl configtest || true

      - name: Start Apache server on port 5000
        run: |
          echo "Starting Apache on port 5000..."
          sudo apachectl -f /etc/apache2/apache2.conf -k start || true
          sleep 3
          curl -I http://localhost:5000 || true

      - name: Start cloudflared tunnel for site and show public URL
        run: |
          echo "🌍 Opening tunnel to http://localhost:5000 ..."
          nohup /usr/local/bin/cloudflared tunnel --url "http://localhost:5000" --no-autoupdate > cloudflared_site.log 2>&1 &
          sleep 10
          if grep -Eo 'https?://[^ ]+trycloudflare.com' cloudflared_site.log | head -n1 > /tmp/public_url; then
            echo "✅ Public site URL:"
            cat /tmp/public_url
          else
            echo "⚠️ Không tìm thấy URL trong cloudflared_site.log. Dump file:"
            sed -n '1,200p' cloudflared_site.log || true
            exit 1
          fi

          echo "🔍 Kiểm tra log Apache (nếu lỗi 500)..."
          sudo tail -n 40 /var/log/apache2/error.log || true

          echo "🕒 Giữ runner hoạt động 6000s để web online..."
          sleep 6000
