name: phpMyAdmin + NRO Setup with Cloudflared Tunnel

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1️⃣ Cài MySQL, PHP, phpMyAdmin, SSH
      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-server php php-mbstring php-zip php-gd php-json php-curl php-mysql unzip wget openssh-client

      # 2️⃣ Dừng MySQL nếu đang chạy
      - name: Stop MySQL service
        run: |
          sudo systemctl stop mysql || true

      # 3️⃣ Khởi động MySQL bỏ qua kiểm tra user/password
      - name: Start MySQL with skip-grant-tables
        run: |
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld
          sudo mysqld_safe --skip-grant-tables --skip-networking &
          sleep 8

      # 4️⃣ Set root password
      - name: Set root password
        run: |
          mysql -uroot <<'SQL'
          FLUSH PRIVILEGES;
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
          FLUSH PRIVILEGES;
          SQL
          echo "✅ Root password set to 'root'"

      # 5️⃣ Restart MySQL bình thường
      - name: Restart MySQL service
        run: |
          sudo pkill mysqld || true
          sudo systemctl start mysql
          sleep 5
          mysql -uroot -proot -e "SELECT VERSION();"
          echo "✅ MySQL restarted and accessible."

      # 6️⃣ Tạo database nro_acc và nro_data từ SQL file
      - name: Create databases and import SQL
        run: |
          # nro_acc
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS nro_acc;"
          mysql -uroot -proot nro_acc < ./nro_acc.sql
          
          # nro_data
          mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS nro_data;"
          mysql -uroot -proot nro_data < ./nro_data.sql
          
          echo "✅ Databases nro_acc and nro_data created and imported."

      # 7️⃣ Tạo user admin (tùy chọn)
      - name: Create admin user
        run: |
          mysql -uroot -proot -e "CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '123456';"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"
          echo "✅ Admin user created."

      # 8️⃣ Cài phpMyAdmin
      - name: Install phpMyAdmin
        run: |
          wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip -O pma.zip
          unzip pma.zip
          mv phpMyAdmin-* phpmyadmin
          sudo php -S 0.0.0.0:8080 -t phpmyadmin &

      # 9️⃣ Cài cloudflared
      - name: Install cloudflared
        run: |
          echo "📥 Installing cloudflared..."
          wget -q -O /usr/local/bin/cloudflared \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          sudo chmod +x /usr/local/bin/cloudflared
          cloudflared --version

      # 🔟 Chạy cloudflared tunnel ephemeral
      - name: Start cloudflared tunnel (ephemeral) and show public URL
        run: |
          echo "🌐 Starting cloudflared tunnel to http://localhost:8080 ..."
          # chạy cloudflared ở background, ghi log vào file để dò URL
          nohup /usr/local/bin/cloudflared tunnel --url http://localhost:8080 --no-autoupdate > cloudflared.log 2>&1 &
          # đợi một chút để cloudflared khởi tạo và in ra URL
          sleep 6
          # thử grep URL dạng trycloudflare.com (ephemeral public URL)
          if grep -Eo 'https?://[^ ]+trycloudflare.com' cloudflared.log | head -n1 > /tmp/pma_url; then
            echo "✅ Public phpMyAdmin URL (ephemeral):"
            cat /tmp/pma_url
          else
            echo "⚠️ Không tìm thấy URL trong log. In ra nội dung cloudflared.log để debug:"
            tail -n +1 cloudflared.log
            exit 1
          fi
          sleep 6000
